### ISSUE TITLE
Broken Tests on Windows (broken conda-forge GDAL/netCDF)

### ISSUE THREAD

**Issue by omad** [corteva/rioxarray#1] opened 2019-04-17 02:51 UTC
#### Problem description
The [Windows CI builds are failing](https://ci.appveyor.com/project/snowman2/rioxarray/builds/23891936#L507). I can reproduce this locally with a conda-forge environment.

This is a problem with the `conda-forge` GDAL builds. In the call to `xarray.open_rasterio()` in the tests the NetCDF file is being opened as HDF5, and so not including useful transform and coordinate information.

It is very similar to https://gis.stackexchange.com/questions/179132/gdal-nc-rasters-opened-as-netcdf-network-common-data-format-under-linux-an , but with `conda-forge` instead of OSGEO packages.

#### More information

From the command line, I see the same behaviour using `rio info` and `gdalinfo`. I can work around it with `gdalinfo NETCDF:MODIS_ARRAY.nc`, which forces the use of the NetCDF driver. Unfortunately, specifying the driver with `rasterio.open('MODIS_ARRAY.nc', driver='netCDF')` doesn't work, with a `not recognized as a supported file format.` error.

I've also tried setting the environment variable `GDAL_SKIP=HDF5 HDF5Image`, but gdal and rasterio both fail to load the file at all.

It's definitely a build issue and not related to these test NetCDFs because I get the same errors with other NetCDF files. 

With `CPL_DEBUG=ON`, `gdalinfo` includes in it's log when opening the file:
```
GDAL_netCDF: driver detected file type=5, libnetcdf detected type=3
Warning 1: NetCDF driver detected file type=5, but libnetcdf detected type=3
```

#### What next
Find time to fix the conda-forge Windows GDAL build.

It will be missing the correct libnetcdf or environment variable. There could be an old osgeo ticket with more information about the problem being fixed in their packaging.

#### Update
The osgeo4w ticket I was thinking of is https://trac.osgeo.org/osgeo4w/ticket/521 , it may or may not be the same fix for the `conda-forge` gdal builds.

**Comment by snowman2** [comment] 2019-04-17 13:18
Thanks for the info @omad! @alfredoahds did you have to do something related to this for a GDAL build?

**Comment by alfredoahds** [comment] 2019-04-17 13:26
I've dealt with this issue before, but I haven't had to handle it in a CI build so I don't have a quick snippet that would fix it. Let me see if I can dig up the build opts I used.

**Comment by alfredoahds** [comment] 2019-04-17 13:29
So from some random notes file I've got, the issue is related to the flags used when compiling HDF4, specifically that you have to disable netcdf in hdf4 otherwise it'll hijack the driver for netcdf files. This is a process that I've used to get everything working as expected:
```bash
apt-get install zlib1g-dev libproj-dev

curl -L "https://www.hdfgroup.org/package/source-gzip-4/?wpdmdl=13048&refresh=5c5dbfc7b25761549647815" | tar zxf - && \
    cd hdf5-1.10.4 && \
    ./configure --with-zlib --prefix=/usr/local --enable-hl && make install

wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz && \
    tar -xzf hdf-4.2.13.tar.gz && cd hdf-4.2.13 && \
    ./configure --enable-shared --disable-netcdf --disable-fortran --prefix=${H4DIR} && \
    make install

export H4DIR=/usr/local
export H5DIR=/usr/local
wget https://github.com/Unidata/netcdf-c/archive/v4.6.2-rc1.tar.gz && \
    tar -xzf v4.6.2-rc1.tar.gz && \
    cd netcdf-c-4.6.2-rc1/ && \
    CPPFLAGS='-I${H5DIR}/include -I${H4DIR}/include' LDFLAGS='-L${H5DIR}/lib -L${H4DIR}/lib -lcurl' ./configure --enable-hdf4 --enable-hdf4-file-tests \
    --enable-hdf4 --enable-hdf4-file-tests --prefix /usr/local/ && \
    make install

# This needs to return with 0 errors, otherwise it won't work. 
make check
    
curl -L http://download.osgeo.org/gdal/2.4.0/gdal-2.4.0.tar.gz | tar zxf - && \
cd gdal-2.4.0/ && \
./configure --prefix=/usr/local --with-python=python3.6 \
            --with-ogr \
            --with-geos \
            --with-expat \
            --with-libz=internal \
            --with-libtiff=internal \
            --with-geotiff=internal \
            --with-netcdf=/usr/local/ \
            --with-png=internal \
            --with-jpeg=internal \
            --with-hdf4=/usr/local/ \
            --with-hdf5=/usr/local/ \
            --with-jasper \
            --with-curl \
            --with-sqlite3 \
            --with-proj 
make -j4 && \
make install && \
cd swig/python &&
python setup.py install
```

**Comment by snowman2** [comment] 2019-06-20 12:29
Resolved by https://github.com/conda-forge/gdal-feedstock/issues/279

**Closed by snowman2** 2019-06-20 12:29 UTC
Labels: help wanted
