### ISSUE TITLE
to_raster writes geotiffs with no CRS

### ISSUE THREAD

**Issue by arkanoid87** [corteva/rioxarray#112] opened 2020-05-04 02:38 UTC
```
$ conda list | grep rioxarray
rioxarray                 0.0.26                     py_0    conda-forge
```

dataarray correctly states CRS
```
>>> mygrid.rio.crs
CRS.from_epsg(32632)
```
rioxarray generates file with no error
```
>>> mygrid.rio.to_raster("mygrid.tif", compress='LZW', tiled=True, dtype="int8")
```

gdalinfo shows empty coordinate system, also tried with qgis
```
$ gdalinfo mygrid.tif
Driver: GTiff/GeoTIFF
Files: mygrid.tif
Size is 1436, 2718
Coordinate System is `'
Origin = (426600.000000000000000,4573500.000000000000000)
Pixel Size = (100.000000000000000,-100.000000000000000)
Metadata:
  categorical_mapping=type_categories
  grid_mapping=spatial_ref
  long_name=type
  name=type
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  426600.000, 4573500.000) 
Lower Left  (  426600.000, 4301700.000) 
Upper Right (  570200.000, 4573500.000) 
Lower Right (  570200.000, 4301700.000) 
Center      (  498400.000, 4437600.000) 
Band 1 Block=256x256 Type=Byte, ColorInterp=Gray
  Description = type
  NoData Value=-1
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
```

EDIT: found workaround with rasterio.
```
mygrid.rio.to_raster("mygrid.tif", compress='LZW', tiled=True, dtype="int8")
with rasterio.open("mygrid.tif", mode='r+') as src:
    src.crs = mygrid.rio.crs
```

**Comment by snowman2** [comment] 2020-05-04 13:15
@arkanoid87, thanks for the report. To help with debugging, mind adding:

1. Output of `python -c `import rioxarray; rioxarray.show_versions()`
2. Output of `gdalinfo --version`
3. An example file to test with?

**Comment by snowman2** [comment] 2020-05-04 13:24
Also, what is the output of `rio info mygrid.tif`?

**Comment by arkanoid87** [comment] 2020-05-04 15:10
> Hmmm, what is the value for the environment variable PROJ_LIB?

```
import os
os.environ['PROJ_LIB']
KeyError: 'PROJ_LIB'
```

**Comment by snowman2** [comment] 2020-05-04 15:23
Did you activate your environment in `conda`? 
```
conda activate <environment_name>
```

**Comment by arkanoid87** [comment] 2020-05-04 15:27
> Did you activate your environment in `conda`?
> 
> ```
> conda activate <environment_name>
> ```

I'm already into conda environment
I'm launching commands into the web terminal of stock jupyter datascience-notebook https://hub.docker.com/r/jupyter/datascience-notebook/

```
(base) jovyan@b40fa0fdd812:~$ conda env list
# conda environments:
#
base                  *  /opt/conda

(base) jovyan@b40fa0fdd812:~$
```

**Comment by snowman2** [comment] 2020-05-04 15:47
The reason I asked is when you activate your environment, the conda activation scripts should set these environment variables for everything to work properly:
```
conda create --n rioxarray rioxarray
conda activate rioxarray
(rioxarray) $ env | grep PROJ
PROJ_LIB=~/miniconda/envs/rioxarray/share/proj
(rioxarray) $ env | grep GDAL
GDAL_DATA=~/miniconda/envs/rioxarray/share/gdal
```

**Comment by snowman2** [comment] 2020-05-18 14:59
I am unable to replicate this. Closing as I assume it is related to the environment setup. Feel free to reopen if you have further details linking the issue to `rioxarray`.

**Closed by snowman2** 2020-05-18 14:59 UTC
Labels: installation-issues

**Comment by sofstef** [comment] 2022-01-23 19:08
I am having this problem as well both when using google colab and a local conda environment. I thought it might be an issue with miniforge, but I tried using a miniconda distribution and that didn't fix it (although something weird happened and it seemed to work the first time I ran the notebook and then I couldn't reproduce that). Here's a demonstration of what happens: 

<img width="567" alt="Screenshot 2022-01-23 at 18 17 17" src="https://user-images.githubusercontent.com/37108884/150692245-451fc272-883e-4cd7-919e-bc87f2249b57.png">

Output of `python -c "import rioxarray; rioxarray.show_versions()"`:

`rioxarray (0.9.1) deps:
  rasterio: 1.2.10
    xarray: 0.20.2
      GDAL: 3.4.1

Other python deps:
     scipy: 1.7.3
    pyproj: 3.3.0

System:
    python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:38:53)  [Clang 11.1.0 ]
executable: ~/miniforge3/envs/rxr/bin/python
   machine: macOS-12.1-x86_64-i386-64bit`

Here are the environment variable outputs: 

`(rxr) %  env | grep PROJ
PROJ_LIB=~/miniforge3/envs/rxr/share/proj
PROJ_NETWORK=ON
(rxr) % env | grep GDAL
GDAL_DATA=~/miniforge3/envs/rxr/share/gdal`

**Comment by snowman2** [comment] 2022-01-24 14:25
@sofstef, it is likely due to the longitude data being from 0-360 for ERA5 data. I recommend converting to -180-180 before writing to tiff, see #58.

**Comment by sofstef** [comment] 2022-01-24 21:42
@snowman2 the ERA5 data had already been processed and longitude was in the [-180, 180]. Oddly enough saving the crs worked when I tried the notebook again and I hadn't changed anything so still have no idea why this was happening. 🤷🏻‍♀️
