### ISSUE TITLE
New value appears after reproject match

### ISSUE THREAD

**Issue by Meresmata** [corteva/rioxarray#195] opened 2020-12-11 11:14 UTC
I want to reproject a raster with reproject_match with an other raster. But during that a new value of 55536  appears.

field_classes -> data to reproject
example_tif -> data to reproject with

`np.unique(field_classes.data)`, output: [1 55537]
`np.unique(example_tif.data)`, output: [21 55537]
`np.unique(field_classes.rio.reproject_match(example_tif).data)`, output: [1 55536 55537]

The Nodata value is 55537, resolution is always 10, -10 (meters)

The extra values are not single spots, but some local areas of a size of one to few houses.

Versions: 

 - rioxarray version: 0.1.1
 - rasterio version: 1.1.7
 - GDAL version: 3.1.3
 - Python version: 3.7
 - Operation System Information: Windows 10

#### Installation method
pypi, instead for rasterio and GDAL using destinct windows buildts

#### Conda environment information (if you installed with conda):

using pyenv

**Comment by snowman2** [comment] 2020-12-11 13:48
Is it possible to provide:
- The input files
- The nodata value for each raster

**Comment by snowman2** [comment] 2020-12-15 14:54
@Meresmata Based on the limited information you have provided, there are several different scenarios that could cause this. My current thinking is that it has to do with information loss. See docs for [managing information loss](https://corteva.github.io/rioxarray/stable/getting_started/manage_information_loss.html).

However, there could also be a bug. If you could provide the minimum code/input data to re-produce this issue so we can dig further into the matter, that would be very helpful. Thanks :+1:

**Comment by Meresmata** [comment] 2020-12-17 09:33
I think found the error, while trying to minimize my example code.
When I rewrote the code, some lines, throw errors, what I remembered, still for this example no error is thrown. The error is caused by 
a) mixture problems in the dimension and 
b) using a *numpy.where(cond, 1, raster.rio.nodata)*, which only made sense for the first dimension.

- I use a *three* band raster (with, no *nodata*, therefore I set it manually). 
- But the error happens when I use reproject_match with a *one* band raster. Than for some spots the 55536 appears. 
- My guess, depending on how, *nodata* are distributed on this location on this three bands. This error does not happen when I only use the first band.

*Code:*
```
import numpy as np
import rioxarray as rxa

field_classes = rxa.open_rasterio("Path to 3 band tif")  # classification layer

print(field_classes.rio.nodata)
print(field_classes.data.shape)
if not field_classes.rio.nodata:
    field_classes.rio.write_nodata(55537, inplace=True)

field_classes.data = np.where((np.where(field_classes.data == 21, 1, field_classes.rio.nodata) != field_classes.rio.nodata),
                              fields,
                              field_classes.rio.nodata)
print(np.unique(field_classes.data))
print(field_classes.data.dtype)


example_tif = rxa.open_rasterio("Path to 1 band, example to match")
print(example_tif.data.shape)
field_classes = field_classes.rio.reproject_match(example_tif)
print(field_classes.shape)
print(np.unique(field_classes.data))
```

*Output:*

> None
> (3, 5912, 7719)
> [    1 55537]
> int32
> (1, 5912, 7719)
> (3, 5912, 7719)
> [    1 55536 55537]

**Comment by snowman2** [comment] 2020-12-18 00:52
@Meresmata are you able to provide example input data that produces this issue?

**Comment by Meresmata** [comment] 2020-12-21 12:07
[example_tifs.zip](https://github.com/corteva/rioxarray/files/5724175/example_tifs.zip)

Hi, I created a tiny example. Hope, it helps to find reproduce the error.

**Comment by snowman2** [comment] 2020-12-21 16:06
Unfortunately, I was unable to reproduce the error. I did run into another error which was fixed by modifying this line:

```python
field_classes.data = np.where(field_classes.data == 21, 1, field_classes.rio.nodata).astype(field_classes.dtype)
```

With that change, the output seemed correct to me:
```python
print(np.unique(field_classes.data))
```
```bash
[    1 55537]
```

Here is the information about my environment:
```python
rioxarray.show_versions()
```
```bash
rioxarray (0.1.1) deps:
  rasterio: 1.1.8
    xarray: 0.16.2
      GDAL: 3.1.4

Other python deps:
     scipy: 1.5.3
    pyproj: 2.6.1.post1

System:
    python: 3.9.1 | packaged by conda-forge | (default, Dec  9 2020, 01:12:47)  [GCC 9.3.0]
executable: ~/miniconda/envs/rio/bin/python
   machine: Linux-5.4.0-58-generic-x86_64-with-glibc2.31
```

**Comment by Meresmata** [comment] 2021-01-11 16:39
Hi, 

 so from my take you added the astype method in the changes above.  This totally solved the problem for me. But I don't know why!
Because it only changes the datatype to the one, it already has?

```
rioxarray (0.1.1) deps:
  rasterio: 1.1.7
    xarray: 0.16.1
      GDAL: 3.1.3

Other python deps:
     scipy: 1.5.2
    pyproj: 2.6.1.post1

System:
    python: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
executable: e:\___svn\cop4ee-2\landcover\code\venv\scripts\python.exe
   machine: Windows-10-10.0.19041-SP0
```

**Comment by snowman2** [comment] 2021-01-11 16:54
The reason I made the dtype change is because numpy made the where into an `Int64` which GDAL does not support (https://github.com/OSGeo/gdal/issues/3325). But, your process does not need `Int64` and I don't know how you got around it before. I am not sure why it removed the error for you, but I am glad to hear that it worked :+1:

**Closed by snowman2** 2021-01-11 16:54 UTC
Labels: bug
